// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test1', function() {
  this.timeout(30000)
  let driver
  let vars
//  beforeEach(async function() {
//    driver = await new Builder().forBrowser('chrome').build()
//    vars = {}
//  })
//  afterEach(async function() {
//    await driver.quit();
//  })
  it('Test1', async function() {
	  assert.equal(0, 0);
  //  await driver.get("https://thedrag.appspot.com/html/home.html")
    //await driver.manage().window().setRect(1936, 1066)
//    await driver.findElement(By.linkText("Car")).click()
//    await driver.findElement(By.css(".card:nth-child(6)")).click()
//    await driver.findElement(By.css(".card:nth-child(6) .np-img-wrapper")).click()
//    await driver.findElement(By.css(".offset-xl-2 > a:nth-child(1) .card-body")).click()
//    await driver.findElement(By.css(".card:nth-child(83) > a")).click()
//    await driver.findElement(By.linkText("Browse by Dealer")).click()
//    await driver.findElement(By.linkText("4")).click()
//    await driver.findElement(By.linkText("About")).click()
//    await driver.findElement(By.linkText("Browse by Car")).click()
//    await driver.findElement(By.linkText("5")).click()
  })
})
