package SeleniumTesting;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://thedrag.appspot.com/");
    driver.manage().window().setSize(new Dimension(1936, 1066));
    driver.findElement(By.linkText("Car")).click();
    driver.findElement(By.cssSelector(".card:nth-child(1) .np-img-wrapper")).click();
    driver.findElement(By.cssSelector(".offset-xl-2 > a:nth-child(1) .card-title")).click();
    driver.findElement(By.cssSelector(".card:nth-child(102) > a")).click();
    driver.findElement(By.linkText("About")).click();
    driver.findElement(By.linkText("Browse by Dealer")).click();
    driver.findElement(By.cssSelector(".card:nth-child(7) > a:nth-child(1)")).click();
    driver.findElement(By.linkText("2020 Toyota Corolla L")).click();
    driver.findElement(By.linkText("Browse by Car")).click();
    driver.findElement(By.cssSelector(".navbar-brand")).click();
    driver.findElement(By.linkText("Dealer")).click();
    driver.findElement(By.linkText("3")).click();
    driver.findElement(By.linkText("5")).click();
    driver.findElement(By.cssSelector(".card:nth-child(1) > a:nth-child(1)")).click();
    driver.findElement(By.linkText("Browse by Model")).click();
    driver.findElement(By.cssSelector(".page-item:nth-child(9) span:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".card:nth-child(2) p:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".offset-xl-2 > a:nth-child(1) .card-body")).click();
  }
}
